repos:
  - repo: local
    hooks:
      - id: unit-test
        name: Unit test + coverage
        entry: python -m pytest tests/ --cov --cov-fail-under=80
        language: system
        pass_filenames: false
        always_run: true
