repos:
  - repo: local
    hooks:
      - id: unit-test
        name: Unit test + Coverage
        entry: python -m pytest tests/ --cov --cov-fail-under=100
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-check
        name: Ruff Lint
        entry: .venv/bin/ruff check
        language: system
        types: [python]

      - id: ruff-format
        name: Ruff Formatting
        entry: .venv/bin/ruff format
        language: system
        types: [python]

      - id: mypy
        name: Mypy
        entry: .venv/bin/mypy
        language: system
        types: [python]

      - id: pyright
        name: Pyright
        entry: .venv/bin/pyright
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: .venv/bin/python -m pylint
        language: system
        types: [python]
