version: "1"

services:
  postgres:
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    networks:
      - postgres-network
    ports:
      - ${PG_PORT}:5432

  adminer:
    image: adminer:5.4.1
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - postgres-network
    depends_on:
      - postgres


  # mongotest:
  #   env_file:
  #     - .env
  #   image: mongo:focal
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  #   networks:
  #     - mongo-network
  #   ports:
  #     - "${MONGO_PORT}:27017"

  

  # mongoexpresstest:
  #   image: mongo-express
  #   container_name: mongo-test-webview
  #   restart: always
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongotest:27017/
  #   networks:
  #     - mongo-network
  #   ports:
  #     - 3531:8081
  #   depends_on:
  #     - mongotest

networks:
  postgres-network:
    driver: bridge

  mongo-network:
    driver: bridge
